# Generated by Django 3.2.7 on 2021-09-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_alter_ads_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='content',
            field=models.TextField(verbose_name='Текст объявления'),
        ),
    ]
