# Generated by Django 3.2.7 on 2021-09-27 09:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_alter_ads_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст объявления'),
        ),
    ]
