# Generated by Django 3.2.7 on 2021-09-29 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_alter_ads_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='ads_response',
            field=models.TextField(default=1, verbose_name='Отклик'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AdsResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_response', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ads.ads')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
            },
        ),
    ]
